# #
#   @usage              https://github.com/ConfigServer-Software/service-blocklists
#   @type               github workflow
#   @updated            09.28.25
#   @usage              generates a list of ipsets which can then be used within host files, config server firewall, and various other apps
#
#   
#   @secrets            secrets.SELF_TOKEN                                          self github personal access token (fine-grained)
#                       secrets.SELF_TOKEN_CL                                       self github personal access token (classic)
#                       secrets.NPM_TOKEN                                           self npmjs access token
#                       secrets.PYPI_API_TOKEN                                      self Pypi API token (production site) - https://pypi.org/
#                       secrets.PYPI_API_TEST_TOKEN                                 self Pypi API token (test site) - https://test.pypi.org/
#                       secrets.SELF_DOCKERHUB_TOKEN                                self Dockerhub token
#                       secrets.CODECOV_TOKEN                                       codecov upload token for nodejs projects
#                       secrets.API_GEOLITE2_KEY                                    maxmind API token
#                       secrets.CF_ACCOUNT_ID                                       cloudflare account id
#                       secrets.CF_ACCOUNT_TOKEN                                    cloudflare account token
#                       secrets.ARTIFACTS_DOMAIN                                    github artifacts domain name
#                       secrets.ARTIFACTS_PORT                                      github artifacts port
#                       secrets.ARTIFACTS_GITHUB_SSH_PRIVATE_KEY                    github artifacts server ssh private key
#                       secrets.ORG_TOKEN                                           org github personal access token (fine-grained)
#                       secrets.ORG_TOKEN_CL                                        org github personal access token (classic)
#                       secrets.ORG_DOCKERHUB_TOKEN                                 org dockerhub secret
#                       secrets.ORG_GITEA_TOKEN                                     org gitea personal access token (classic) with package:write permission
#                       secrets.BOT_GPG_KEY_ASC                                     bot gpg private key (armored) | BEGIN PGP PRIVATE KEY BLOCK
#                       secrets.BOT_GPG_KEY_B64                                     bot gpg private key (binary) converted to base64
#                       secrets.BOT_GPG_PASSPHRASE                                  bot gpg private key passphrase
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_RELEASES                discord webhook to report release notifications from github to discord
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_WORKFLOWS               discord webhook to report workflow notifications from github to discord
#                       secrets.DISCORD_WEBHOOK_CHAN_GITHUB_UPDATES                 discord webhook to report activity notifications from github to discord
#   
#   @local              these workflows can be tested locally through the use of `act`
#                           https://github.com/nektos/act
#                       Extract act to folder
#                       Add system env var with path to act.exe
#                       Run the commands:
#                           git pull https://github.com/username/repo
#                           act -W .github/workflows/blocklist-generate.yml -P ubuntu-latest=catthehacker/ubuntu:full-22.04
#                           act -W .github/workflows/blocklist-generate.yml -s TOKEN_CL=XXXXXXXXXX --pull=false
#   
#   📄 bl-master.sh               generate master ipset | URLs: VARARG
#   📄 bl-plain.sh                generate ipset from online plain-text url / page | URLs: VARARG
#   📄 bl-json.sh                 generate ipset from json formatted web url. requires url and jq query | URLs: SINGLE
#   📄 bl-htmlip.sh               generate ipset by fetching HTML in web url, pulls only ips with grep rule (cant be changed) | URLs: SINGLE
#   📄 bl-html.sh                 generate ipset by fetching HTML in web url, does not run its own grep, must be specified in command | URLs: VARARG
#   📄 bl-block.sh                generate ipset by fetching locally specified file in /blocks/ repo folder
#   📄 bl-format.sh               generate ipset by from an existing list of IPs. does not generate ips itself. only validates a list provided
#   📄 bl-spf.sh                  generate ipset by fetching _spf ips from domain
#   
#   local test requires the same structure as the github workflow
#       📁 .github
#           📁 blocks
#               📁 bruteforce
#                   📄 01.ipset
#               📁 privacy
#                   📄 01.ipset
#           📁 scripts
#               📄 bl-master.sh
#               📄 bl-plain.sh
#               📄 bl-json.sh
#               📄 bl-htmlip.sh
#               📄 bl-html.sh
#               📄 bl-block.sh
#               📄 bl-format.sh
#               📄 bl-spf.sh
#           📁 workflows
#               📄 blocklist-generate.yml
# #

name: '🧱 Blocklist › Generate'
run-name: '🧱 Blocklist › Generate'

# #
#   triggers
# #

on:

    # #
    #   Trigger › Workflow Dispatch
    # #

    workflow_dispatch:
      inputs:

        # #
        #   true:     runs all actions, even ones not scheduled
        #   false:    only scheduled tasks will run
        # #
  
        RUN_ALL_ACTIONS:
            description:  '📑 Run All Actions'
            required:     true
            default:      false
            type:         boolean

    # #
    #   Trigger › Cron Schedule
    # #

    schedule:
    # - cron: '0 2,8,14,20 * * *'
      - cron: '0 */12 * * *'

# #
#   environment variables
# #

env:
    ASSIGN_USER:                    Aetherinox
    BOT_NAME_1:                     BinaryServ
    BOT_NAME_DEPENDABOT:            dependabot[bot]
    BOT_NAME_RENOVATE:              renovate[bot]
    GPG_KEY_BASE64:                 ${{ secrets.ADMINSERV_GPG_KEY_B64 }}
    GPG_KEY_PASSPHRASE:             ${{ secrets.ADMINSERV_GPG_PASSPHRASE }}
  
# #
#   jobs
# #

jobs:

    # #
    #   Job › Setup
    # #

    blocklist-setup:
        name: >-
          📦 Setup
        runs-on: ubuntu-latest
      # runs-on: apollo-x64
        timeout-minutes: 60
        steps:

            # #
            #   Job › Checkout
            # #

            - name: >-
                  ☑️ Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            # #
            #   Job › Job Information
            # #

            - name: >-
                  🔄 Load Job
              uses: qoomon/actions--context@v5
              id: 'context'

            # #
            #   Job › Start
            # #

            - name: >-
                  ✅ Start
              run: |
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo " Starting Job ${{ steps.context.outputs.job_name }}"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

                  YEAR="$(date +'%Y')"
                  echo "YEAR=${YEAR}" >> $GITHUB_ENV

                  NOW="$(date +'%m-%d-%Y %H:%M:%S')"                                                #  02-25-2025 12:49:48
                  echo "NOW=${NOW}" >> $GITHUB_ENV

                  NOW_SHORT="$(date +'%m-%d-%Y')"                                                   #  02-25-2025
                  echo "NOW_SHORT=${NOW_SHORT}" >> $GITHUB_ENV

                  NOW_LONG="$(date +'%m-%d-%Y %H:%M')"                                              #  02-25-2025 12:49
                  echo "NOW_LONG=${NOW_LONG}" >> $GITHUB_ENV

                  NOW_DOCKER="$(date +'%Y%m%d')"                                                    #  20250225
                  echo "NOW_DOCKER=${NOW_DOCKER}" >> $GITHUB_ENV

                  NOW_DOCKER_TS="$(date -u +'%FT%T.%3NZ')"                                          #  2025-02-25T12:50:11.569Z
                  echo "NOW_DOCKER_TS=${NOW_DOCKER_TS}" >> $GITHUB_ENV

                  SHA1="$(git rev-parse HEAD)"                                                      #  71fad013cfce9116ec62779e4a7e627fe4c33627
                  echo "SHA1=${SHA1}" >> $GITHUB_ENV

                  SHA1_GH="$(echo ${GITHUB_SHA})"                                                   #  71fad013cfce9116ec62779e4a7e627fe4c33627
                  echo "SHA1_GH=${SHA1_GH}" >> $GITHUB_ENV

                  PKG_VER_1DIGIT="$(echo ${{ env.IMAGE_VERSION }} | cut -d '.' -f1-1)"              #  15.52.35 > 15
                  echo "PKG_VER_1DIGIT=${PKG_VER_1DIGIT}" >> $GITHUB_ENV

                  PKG_VER_2DIGIT="$(echo ${{ env.IMAGE_VERSION }} | cut -d '.' -f1-2)"              #  15.52.35 > 15.52
                  echo "PKG_VER_2DIGIT=${PKG_VER_2DIGIT}" >> $GITHUB_ENV

                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"
                  sudo apt -qq update
                  sudo apt -qq install tree
                  echo "‎"
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"
                  echo " Runner .............. ${{ runner.name }}"
                  echo " Workflow ............ ${{ github.workflow }} (#${{ github.workflow_ref }})"
                  echo " Run Number .......... ${{ github.run_number }}"
                  echo " Ref ................. ${{ github.ref }}"
                  echo " Ref Name ............ ${{ github.ref_name }}"
                  echo " Event Name .......... ${{ github.event_name }}"
                  echo " Repo ................ ${{ github.repository }}"
                  echo " Repo Owner .......... ${{ github.repository_owner }}"
                  echo " Run ID .............. https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  echo " Triggered By ........ ${{ github.actor }}"
                  echo " SHA 1 (GITHUB_SHA) .. ${GITHUB_SHA}"
                  echo " SHA 2 (github.sha) .. ${{ github.sha }}"
                  echo " SHA 3 (env.SHA1) .... ${SHA1}"
                  echo " SHA 4 (env.SHA1_GH) . ${SHA1_GH}"
                  echo " Workspace ........... ${{ github.workspace }}"
                  echo " PWD ................. ${PWD}"
                  echo " Job Name ............ ${{ steps.context.outputs.job_name }}"
                  echo " Job ID .............. ${{ steps.context.outputs.job_id }}"
                  echo " Job URL ............. ${{ steps.context.outputs.job_url }}"
                  echo " Run ID .............. ${{ steps.context.outputs.run_id }}"
                  echo " Run Attempt ......... ${{ steps.context.outputs.run_attempt }}"
                  echo " Run Number .......... ${{ steps.context.outputs.run_number }}"
                  echo " Run URL ............. ${{ steps.context.outputs.run_url }}"
                  echo " Run Env ............. ${{ steps.context.outputs.environment }}"
                  echo " Run Env URL ......... ${{ steps.context.outputs.environment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Deployment URL .. ${{ steps.context.outputs.deployment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Runner Name ..... ${{ steps.context.outputs.runner_name }}"
                  echo " Run Runner ID ....... ${{ steps.context.outputs.runner_id }}"
                  echo " Year ................ ${YEAR}"
                  echo " Now ................. ${NOW}"
                  echo " Now (Short) ......... ${NOW_SHORT}"
                  echo " Now (Long) .......... ${NOW_LONG}"
                  echo " Now (Docker) ........ ${NOW_DOCKER}"
                  echo " Now (Docker TS) ..... ${NOW_DOCKER_TS}"
                  echo "‎"
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"
                  tree -I node_modules -I .git -I ./
                  echo "‎"
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"

            # #
            #   Generate › Install Packages
            # #

            - name: "🧱 Install Packages"
              run: |
                  sudo apt-get install -y ipcalc ed html2text whois uuid-runtime autoconf

            # #
            #   Generate › Cache Packages
            # #

            - name: "🧱 Cache Packages"
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: ipcalc ed html2text whois uuid-runtime
                  version: 1.0

    # #
    #   Job › Blocklist › Master
    # #

    blocklist-generate:
        name: >-
          📋 Generate › Blocklist
        runs-on: ubuntu-latest
      # runs-on: apollo-x64
        timeout-minutes: 60
        needs: [ blocklist-setup ]
        outputs:
            artifact-name: ${{ steps.generate_artifact_zip.outputs.artifact-name }}
            artifact-path: ${{ steps.generate_artifact_zip.outputs.artifact-path }}
        steps:

            # #
            #   Generate › Checkout
            # #

            - name: >-
                  ☑️ Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            # #
            #   Generate › Job Information
            # #

            - name: >-
                  🔄 Load Job
              uses: qoomon/actions--context@v4
              id: 'context'

            # #
            #   Generate › Start
            # #

            - name: >-
                  ✅ Start
              run: |
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo " Starting Job ${{ steps.context.outputs.job_name }}"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

                  YEAR="$(date +'%Y')"
                  echo "YEAR=${YEAR}" >> $GITHUB_ENV

                  NOW="$(date +'%m-%d-%Y %H:%M:%S')"                                                #  02-25-2025 12:49:48
                  echo "NOW=${NOW}" >> $GITHUB_ENV

                  NOW_SHORT="$(date +'%m-%d-%Y')"                                                   #  02-25-2025
                  echo "NOW_SHORT=${NOW_SHORT}" >> $GITHUB_ENV

                  NOW_LONG="$(date +'%m-%d-%Y %H:%M')"                                              #  02-25-2025 12:49
                  echo "NOW_LONG=${NOW_LONG}" >> $GITHUB_ENV

                  NOW_DOCKER="$(date +'%Y%m%d')"                                                    #  20250225
                  echo "NOW_DOCKER=${NOW_DOCKER}" >> $GITHUB_ENV

                  NOW_DOCKER_TS="$(date -u +'%FT%T.%3NZ')"                                          #  2025-02-25T12:50:11.569Z
                  echo "NOW_DOCKER_TS=${NOW_DOCKER_TS}" >> $GITHUB_ENV

                  SHA1="$(git rev-parse HEAD)"                                                      #  71fad013cfce9116ec62779e4a7e627fe4c33627
                  echo "SHA1=${SHA1}" >> $GITHUB_ENV

                  SHA1_GH="$(echo ${GITHUB_SHA})"                                                   #  71fad013cfce9116ec62779e4a7e627fe4c33627
                  echo "SHA1_GH=${SHA1_GH}" >> $GITHUB_ENV

                  PKG_VER_1DIGIT="$(echo ${{ env.IMAGE_VERSION }} | cut -d '.' -f1-1)"              #  15.52.35 > 15
                  echo "PKG_VER_1DIGIT=${PKG_VER_1DIGIT}" >> $GITHUB_ENV

                  PKG_VER_2DIGIT="$(echo ${{ env.IMAGE_VERSION }} | cut -d '.' -f1-2)"              #  15.52.35 > 15.52
                  echo "PKG_VER_2DIGIT=${PKG_VER_2DIGIT}" >> $GITHUB_ENV

                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"
                  sudo apt -qq update
                  sudo apt -qq install tree
                  echo "‎"
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"
                  echo " Runner .............. ${{ runner.name }}"
                  echo " Workflow ............ ${{ github.workflow }} (#${{ github.workflow_ref }})"
                  echo " Run Number .......... ${{ github.run_number }}"
                  echo " Ref ................. ${{ github.ref }}"
                  echo " Ref Name ............ ${{ github.ref_name }}"
                  echo " Event Name .......... ${{ github.event_name }}"
                  echo " Repo ................ ${{ github.repository }}"
                  echo " Repo Owner .......... ${{ github.repository_owner }}"
                  echo " Run ID .............. https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  echo " Triggered By ........ ${{ github.actor }}"
                  echo " SHA 1 (GITHUB_SHA) .. ${GITHUB_SHA}"
                  echo " SHA 2 (github.sha) .. ${{ github.sha }}"
                  echo " SHA 3 (env.SHA1) .... ${SHA1}"
                  echo " SHA 4 (env.SHA1_GH) . ${SHA1_GH}"
                  echo " Workspace ........... ${{ github.workspace }}"
                  echo " PWD ................. ${PWD}"
                  echo " Job Name ............ ${{ steps.context.outputs.job_name }}"
                  echo " Job ID .............. ${{ steps.context.outputs.job_id }}"
                  echo " Job URL ............. ${{ steps.context.outputs.job_url }}"
                  echo " Run ID .............. ${{ steps.context.outputs.run_id }}"
                  echo " Run Attempt ......... ${{ steps.context.outputs.run_attempt }}"
                  echo " Run Number .......... ${{ steps.context.outputs.run_number }}"
                  echo " Run URL ............. ${{ steps.context.outputs.run_url }}"
                  echo " Run Env ............. ${{ steps.context.outputs.environment }}"
                  echo " Run Env URL ......... ${{ steps.context.outputs.environment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Deployment URL .. ${{ steps.context.outputs.deployment_url }}"
                  echo " Run Deployment ...... ${{ steps.context.outputs.deployment_id }}"
                  echo " Run Runner Name ..... ${{ steps.context.outputs.runner_name }}"
                  echo " Run Runner ID ....... ${{ steps.context.outputs.runner_id }}"
                  echo " Year ................ ${YEAR}"
                  echo " Now ................. ${NOW}"
                  echo " Now (Short) ......... ${NOW_SHORT}"
                  echo " Now (Long) .......... ${NOW_LONG}"
                  echo " Now (Docker) ........ ${NOW_DOCKER}"
                  echo " Now (Docker TS) ..... ${NOW_DOCKER_TS}"
                  echo "‎"
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"
                  tree -I node_modules -I .git -I ./
                  echo "‎"
                  echo "‎"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "‎"
                  echo "‎"

            # #
            #   Generate › Install Packages
            # #

            - name: "🧱 Install Packages"
              run: |
                  sudo apt-get install -y ipcalc ed html2text whois uuid-runtime autoconf

            # #
            #   Generate › Cache Packages
            # #

            - name: "🧱 Cache Packages"
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: ipcalc ed html2text whois uuid-runtime
                  version: 1.0

            # #
            #   Generate › Configure
            #   
            #   this step installs packages we need to manage ipsets.
            #       - iprange
            #         this package allows us to convert ip ranges into a CIDR formatted ip
            #         10.10.0.1-10.10.0.9  =>   10.10.0.1
            #                                   10.10.0.2/31
            #                                   10.10.0.4/30
            #                                   10.10.0.8/31
            #       https://github.com/firehol/iprange
            # #

            - name: '⚙️ Configure'
              id: task_blocklist_generate_configure
              run: |
                  git clone https://github.com/firehol/iprange.git ./.temp/iprange
                  cd .temp/iprange
                  ./autogen.sh
                  ./configure --disable-man
                  sudo make && make install

            # #
            #   Release › Dockerhub › Install Dependencies
            # #

            - name: '📦 Install Dependencies'
              run:
                  sudo apt-get install -qq dos2unix

            # #
            #   Release › Dockerhub › Execute dos2unix
            # #

            - name: '🔐 Apply dos2unix'
              run: |
                  echo "⚠️⚠️⚠️ Running DOS2UNIX ⚠️⚠️⚠️"
                  find .github/scripts -type f -name "*.sh" -print0 | xargs -0 dos2unix --
                  echo "✅✅✅ Completed DOS2UNIX ✅✅✅"

            # #
            #   Generate › Set Template Permissions
            # #

            - name: "☑️ Set Permissions"
              id: task_blocklist_generate_perms
              run: |
                  echo "🔧 Setting executable permissions for scripts"

                  num_success=0
                  num_failure=0

                  for f in .github/scripts/*.sh; do
                      echo "Setting executable permission on ${f}"
                      chmod 755 "${f}"

                      if [ -x "${f}" ]; then
                          echo "   ✅ ${f} is executable"
                          num_success=$((num_success + 1))
                      else
                          echo "::error file=${f},line=1,title=Permission Failed::Failed to set executable bit"
                          num_failure=$((num_failure + 1))
                      fi
                      echo ""
                  done

                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo "✅ ${num_success} successfully verified"
                  echo "❌ ${num_failure} failed"
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――"

                  if [ "${num_failure}" -gt 0 ]; then
                      exit 1
                  fi

                  echo "🎉 All script permissions verified"

            # #
            #   Generate › Set Env Variables
            # #

            - name: "📦 Set Env Variables"
              id: task_commit_pre
              run: |
                  useragent="${{ vars.BL_GENERAL_USERAGENT }}"
                  echo "USERAGENT=$(echo $useragent)" >> $GITHUB_ENV

            # #
            #   Generate › Master
            # #

            - name: "🧱 Generate › Main"
              id: task_blocklist_generate_master
              run: |
  
                  # #
                  #   Main › Master
                  # #

                  run_master=".github/scripts/bl-master.sh blocklists/master.ipset ${{ secrets.API_01_FILE_01 }} ${{ secrets.API_01_FILE_02 }} ${{ secrets.API_01_FILE_03 }} ${{ secrets.API_01_FILE_04 }} ${{ secrets.API_01_FILE_05 }} ${{ secrets.API_01_FILE_06 }} ${{ secrets.API_01_FILE_07 }} ${{ secrets.API_01_FILE_08 }} ${{ secrets.API_01_FILE_09 }}"
                  eval "./$run_master"

                  # #
                  #   Main › Highrisk
                  # #

                  run_highrisk=".github/scripts/bl-block.sh blocklists/highrisk.ipset highrisk"
                  eval "./$run_highrisk"

                  # #
                  #   Main › BOGON
                  # #

                  run_bogon=".github/scripts/bogon.sh blocklists/bogon.ipset"
                  eval "./$run_bogon"

            # #
            #   Generate › Privacy
            # #

            - name: "🧱 Generate › Privacy"
              id: task_blocklist_generate_privacy
              run: |

                  # #
                  #   Privacy › General
                  # #
  
                  run_general=".github/scripts/bl-block.sh blocklists/privacy/privacy_general.ipset privacy"
                  eval "./$run_general"

                  # #
                  #   Privacy › Activision
                  # #

                  run_activision=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_activision.ipset ${{ vars.BL_PRIVACY_ACTIVISION_SRC }}"
                  eval "./$run_activision"

                  # #
                  #   Privacy › Ahrefs
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_AHREFS_SRC }} | jq -r '.ips[].ip_address | select( . != null )' | .github/scripts/bl-format.sh blocklists/privacy/privacy_ahrefs.ipset

                  # #
                  #   Privacy › AI › ChatGPT
                  # #

                  curl -sSL "${{ vars.BL_PRIVACY_AI_OPENAI_GPTBOT_SRC }}" \
                    | jq -r '.prefixes[] | .ipv4Prefix // .ipv6Prefix' \
                    | sort -u \
                    | .github/scripts/bl-format.sh blocklists/privacy/privacy_ai_openai_gpt_bot.ipset

                  curl -sSL "${{ vars.BL_PRIVACY_AI_OPENAI_GPTCHAT_SRC }}" \
                    | jq -r '.prefixes[] | .ipv4Prefix // .ipv6Prefix' \
                    | sort -u \
                    | .github/scripts/bl-format.sh blocklists/privacy/privacy_ai_openai_gpt_chat.ipset

                  curl -sSL "${{ vars.BL_PRIVACY_AI_OPENAI_SEARCHBOT_SRC }}" \
                    | jq -r '.prefixes[] | .ipv4Prefix // .ipv6Prefix' \
                    | sort -u \
                    | .github/scripts/bl-format.sh blocklists/privacy/privacy_ai_openai_gpt_searchbot.ipset

                  # #
                  #   Privacy › AI › Claude
                  # #

                  curl -sSL "${{ vars.BL_PRIVACY_AI_CLAUDE_SRC }}" \
                    | sed '/Phased out IP addresses/,$d' \
                    | grep -oE '[0-9a-fA-F:.]+/[0-9]+' \
                    | sort -u \
                    | .github/scripts/bl-format.sh blocklists/privacy/privacy_ai_claude_official.ipset

                  # #
                  #   Privacy › Akamai (Cloud / CDN)
                  # #
  
                  AKAMAI_IPv4=$( curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_AKAMAI_SRC }}/akamai_ipv4_CIDRs.txt \
                    | grep -vE '^(#|;|[[:space:]]*$)' )
                  AKAMAI_IPv6=$( curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_AKAMAI_SRC }}/akamai_ipv6_CIDRs.txt \
                    | grep -vE '^(#|;|[[:space:]]*$)' )
                  AKAMAI_LIST=$( echo -e "${AKAMAI_IPv4}\n${AKAMAI_IPv6}" | sort -u )
                  echo "$AKAMAI_LIST" | .github/scripts/bl-format.sh blocklists/privacy/privacy_akamai.ipset

                  # #
                  #   Privacy › Amazon AWS
                  # #

                  run_amz_aws=".github/scripts/bl-json.sh blocklists/privacy/privacy_amazon_aws.ipset ${{ vars.BL_PRIVACY_AMAZON_SRC }} '.prefixes[] | select(.service==\"AMAZON\") | .ip_prefix'"
                  eval "./$run_amz_aws"

                  # #
                  #   Privacy › Amazon EC2
                  # #

                  run_amz_ec2=".github/scripts/bl-json.sh blocklists/privacy/privacy_amazon_ec2.ipset ${{ vars.BL_PRIVACY_AMAZON_SRC }} '.prefixes[] | select(.service==\"EC2\") | .ip_prefix'"
                  eval "./$run_amz_ec2"

                  # #
                  #   Privacy › Anthropic
                  # #

                  run_mip_anthropic=".github/scripts/bl-mip.sh blocklists/privacy/privacy_anthropic.ipset '${{ vars.BL_PRIVACY_MIP_ANTHROPIC_SRC }}' privacy/anthropic"
                  eval "./$run_mip_anthropic"

                  # #
                  #   Privacy › Apple Bot
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_APPLE_BOT_SRC }} | jq -r '.prefixes | .[] |.ipv4Prefix//empty,.ipv6Prefix//empty' | .github/scripts/bl-format.sh blocklists/privacy/privacy_apple_bot.ipset

                  # #
                  #   Privacy › Apple Proxy
                  #   https://developer.apple.com/icloud/prepare-your-network-for-icloud-private-relay/
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_APPLE_PROXY_SRC }} | cut -d',' -f1 | .github/scripts/bl-format.sh blocklists/privacy/privacy_apple_icloud.ipset

                  # #
                  #   Privacy › Automattic / Tumblr / Wordpress
                  # #

                  run_automattic=".github/scripts/bl-whois.sh blocklists/privacy/privacy_automattic.ipset ${{ vars.BL_PRIVACY_AUTOMATTIC_SRC }}"
                  eval "./$run_automattic"

                  # #
                  #   Privacy › Alibaba
                  # #

                  run_alibaba=".github/scripts/bl-whois.sh blocklists/privacy/privacy_alibaba.ipset ${{ vars.BL_PRIVACY_ALIBABA_SRC }}"
                  eval "./$run_alibaba"
                  
                  # #
                  #   Privacy › Baidu
                  # #

                  run_baidu=".github/scripts/bl-whois.sh blocklists/privacy/privacy_baidu.ipset ${{ vars.BL_PRIVACY_BAIDU_SRC }}"
                  eval "./$run_baidu"

                  # #
                  #   Privacy › Bing
                  # #

                  run_bing=".github/scripts/bl-json.sh blocklists/privacy/privacy_bing.ipset ${{ vars.BL_PRIVACY_BING_SRC }} '.prefixes | .[] |.ipv4Prefix//empty,.ipv6Prefix//empty'"
                  eval "./$run_bing"

                  # #
                  #   Privacy › Blizzard
                  # #

                  run_blizzard=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_blizzard.ipset ${{ vars.BL_PRIVACY_BLIZZARD_SRC }}"
                  eval "./$run_blizzard"

                  # #
                  #   Privacy › Bunny CDN
                  # #

                  BUNNYCDN_IPv4=$( curl -sSL ${{ vars.BL_PRIVACY_BUNNYCDN_SRC }}/plain \
                    | grep -vE '^(#|;|[[:space:]]*$)' )
                  BUNNYCDN_IPv6=$( curl -sSL ${{ vars.BL_PRIVACY_BUNNYCDN_SRC }}/ipv6 \
                    | jq -r '.[] | select( . != null )' | grep -vE '^(#|;|[[:space:]]*$)' )
                  BUNNYCDN_LIST=$( echo -e "${BUNNYCDN_IPv4}\n${BUNNYCDN_IPv6}" | sort -u )
                  echo "$BUNNYCDN_LIST" | .github/scripts/bl-format.sh blocklists/privacy/privacy_bunnycdn.ipset

                  # #
                  #   Privacy › ByteDance / Tiktok
                  # #

                  run_bytedance=".github/scripts/bl-whois.sh blocklists/privacy/privacy_bytedance.ipset ${{ vars.BL_PRIVACY_BYTEDANCE_SRC }}"
                  eval "./$run_bytedance"

                  # #
                  #   Privacy › Cloudfront
                  # #

                  run_cloudfront=".github/scripts/bl-json.sh blocklists/privacy/privacy_cloudfront.ipset ${{ vars.BL_PRIVACY_CLOUDFRONT_SRC }} 'map(.[]) | sort | .[]'"
                  eval "./$run_cloudfront"

                  # #
                  #   Privacy › Cloudflare CDN
                  # #

                  CLOUDFLARE_IPv4=$( curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_CLOUDFLARE_SRC }}/ips-v4 \
                    | grep -vE '^(#|;|[[:space:]]*$)' )
                  CLOUDFLARE_IPv6=$( curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_CLOUDFLARE_SRC }}/ips-v6 \
                    | grep -vE '^(#|;|[[:space:]]*$)' )
                  CLOUDFLARE_LIST=$( echo -e "${CLOUDFLARE_IPv4}\n${CLOUDFLARE_IPv6}" | sort -u )
                  echo "$CLOUDFLARE_LIST" | .github/scripts/bl-format.sh blocklists/privacy/privacy_cloudflarecdn.ipset

                  # #
                  #   Privacy › Digital Ocean
                  # #

                  run_digitalocean=".github/scripts/bl-whois.sh blocklists/privacy/privacy_digitalocean_asn.ipset ${{ vars.BL_PRIVACY_DIGITALOCEAN_ASN_SRC }}"
                  eval "./$run_digitalocean"

                  # #
                  #   Privacy › Digital Ocean
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_DIGITALOCEAN_URL_SRC }} \
                    | cut -d, -f1 \
                    | grep -vE '^(#|;|[[:space:]]*$)' \
                    | sort -u \
                    | .github/scripts/bl-format.sh blocklists/privacy/privacy_digitalocean_source.ipset

                  # #
                  #   Privacy › DuckDuckGo
                  #   
                  #   Originally, we crawled DDG's Github docs page. However, it was shut down in 2025.
                  #       curl -sSL -A "${{ env.USERAGENT }}" https://raw.githubusercontent.com/duckduckgo/duckduckgo-help-pages/master/_docs/results/duckduckbot.md | grep "^\- " | awk '{gsub("-",""); print}' | awk '{gsub(/ /,""); print}' | .github/scripts/bl-format.sh blocklists/privacy/privacy_duckduckgo.ipset
                  #   
                  #   Now we use their official json list
                  #       https://duckduckgo.com/duckduckbot.json
                  # #

                  run_duckduckgo=".github/scripts/bl-json.sh blocklists/privacy/privacy_duckduckgo.ipset ${{ vars.BL_PRIVACY_DUCKDUCKGO_SRC }} '.prefixes[] | select(.ipv4Prefix or .ipv6Prefix) | (.ipv4Prefix // .ipv6Prefix)'"
                  eval "./$run_duckduckgo"

                  # #
                  #   Privacy › Electronic Arts & IGN
                  # #

                  run_ea_ign=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_electronicarts_ign.ipset ${{ vars.BL_PRIVACY_ELECTRONICARTS_SRC }}"
                  eval "./$run_ea_ign"

                  # #
                  #   Privacy › Facebook
                  #   https://github.com/SecOps-Institute/FacebookIPLists/blob/master/facebook_asn_list.lst
                  #   https://bgp.he.net/search?search%5Bsearch%5D=facebook&commit=Search
                  # #

                  run_facebook=".github/scripts/bl-whois.sh blocklists/privacy/privacy_facebook.ipset ${{ vars.BL_PRIVACY_FACEBOOK_SRC }}"
                  eval "./$run_facebook"

                  # #
                  #   Privacy › Fastly
                  # #

                  run_fastly=".github/scripts/bl-json.sh blocklists/privacy/privacy_fastly.ipset ${{ vars.BL_PRIVACY_FASTLY_SRC }} 'map(.[]) | .[]'"
                  eval "./$run_fastly"

                  # #
                  #   Privacy › Github
                  #   
                  #   https://api.github.com/meta
                  # #

                  GITHUB_URL="${{ vars.BL_PRIVACY_GITHUB_SRC }}"

                  run_github_all=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_all.ipset $GITHUB_URL '..  | strings | select(test(\"^[0-9a-fA-F:.]+/[0-9]+$\"))'"
                  eval "./$run_github_all"

                  run_github_hooks=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_hooks.ipset $GITHUB_URL '.hooks[]'"
                  eval "./$run_github_hooks"

                  run_github_web=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_web.ipset $GITHUB_URL '.web[]'"
                  eval "./$run_github_web"

                  run_github_api=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_api.ipset $GITHUB_URL '.api[]'"
                  eval "./$run_github_api"

                  run_github_git=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_git.ipset $GITHUB_URL '.git[]'"
                  eval "./$run_github_git"

                  run_github_packages=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_packages.ipset $GITHUB_URL '.packages[]'"
                  eval "./$run_github_packages"

                  run_github_pages=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_pages.ipset $GITHUB_URL '.pages[]'"
                  eval "./$run_github_pages"

                  run_github_importer=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_importer.ipset $GITHUB_URL '.importer[]'"
                  eval "./$run_github_importer"

                  run_github_actions=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_actions.ipset $GITHUB_URL '.actions[]'"
                  eval "./$run_github_actions"

                  run_github_actions_macos=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_actions_macos.ipset $GITHUB_URL '.actions_macos[]'"
                  eval "./$run_github_actions_macos"

                  run_github_codespaces=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_codespaces.ipset $GITHUB_URL '.codespaces[]'"
                  eval "./$run_github_codespaces"

                  run_github_copilot=".github/scripts/bl-json.sh blocklists/privacy/privacy_github_copilot.ipset $GITHUB_URL '.copilot[]'"
                  eval "./$run_github_copilot"

                  # #
                  #   Privacy › Google › Core
                  # #

                  run_google_core=".github/scripts/bl-json.sh blocklists/privacy/privacy_google_core.ipset ${{ vars.BL_PRIVACY_GOOGLE_BOTS_SRC }} '.prefixes[] | select(.ipv4Prefix or .ipv6Prefix) | (.ipv4Prefix // .ipv6Prefix)'"
                  eval "./$run_google_core"

                  # #
                  #   Privacy › Google › Bot
                  # #

                  run_google_bot=".github/scripts/bl-json.sh blocklists/privacy/privacy_google_bots.ipset ${{ vars.BL_PRIVACY_GOOGLE_BOTS_SRC }}'.prefixes | .[] |.ipv4Prefix//empty,.ipv6Prefix//empty'"
                  eval "./$run_google_bot"

                  # #
                  #   Privacy › Google › Cloud
                  # #

                  run_google_cloud=".github/scripts/bl-json.sh blocklists/privacy/privacy_google_cloud.ipset ${{ vars.BL_PRIVACY_GOOGLE_CLOUD_SRC }} '.prefixes[] | select(.ipv4Prefix or .ipv6Prefix) | (.ipv4Prefix // .ipv6Prefix)'"
                  eval "./$run_google_cloud"

                  # #
                  #   Privacy › Huawei
                  # #

                  run_huawei=".github/scripts/bl-whois.sh blocklists/privacy/privacy_huawei.ipset ${{ vars.BL_PRIVACY_HUAWEI_SRC }}"
                  eval "./$run_huawei"

                  # #
                  #   Privacy › Linode
                  # #

                  curl -fsSL "${{ vars.BL_PRIVACY_LINODE_SRC }}" | awk -F',' '{print $1}' | sort -u | .github/scripts/bl-format.sh blocklists/privacy/privacy_linode.ipset

                  # #
                  #   Privacy › Microsoft › 365
                  # #

                  MS_365_URL="${{ vars.BL_PRIVACY_MICROSOFT_365_SRC }}?clientrequestid=$(uuidgen)"
                  run_microsoft_365=".github/scripts/bl-json.sh blocklists/privacy/privacy_microsoft_365.ipset $MS_365_URL '.[] | .ips[]?'"
                  eval "./$run_microsoft_365"

                  # #
                  #   Privacy › Microsoft › Azure
                  #   
                  #   - Public Cloud
                  #   - US Government
                  #   - Germany Cloud
                  #   - China Cloud
                  #   
                  #   @ref    https://azservicetags.azurewebsites.net/
                  # #

                  MS_AZURE_URL_PUBLIC=$( curl -fsSL "${{ vars.BL_PRIVACY_MICROSOFT_AZURE_URL_PUBLIC_SRC }}" | grep -o 'https://download.microsoft.com/download[^"]*ServiceTags_Public_[0-9]\+\.json' | head -n1 )
                  run_microsoft_azure_public=".github/scripts/bl-json.sh blocklists/privacy/privacy_microsoft_azure_public.ipset $MS_AZURE_URL_PUBLIC '.values[].properties.addressPrefixes[]'"
                  eval "./$run_microsoft_azure_public"

                  MS_AZURE_URL_USGOV=$( curl -fsSL "${{ vars.BL_PRIVACY_MICROSOFT_AZURE_URL_USGOV_SRC }}" | grep -o 'https://download.microsoft.com/download[^"]*ServiceTags_AzureGovernment_[0-9]\+\.json' | head -n1 )
                  run_microsoft_azure_usgov=".github/scripts/bl-json.sh blocklists/privacy/privacy_microsoft_azure_usgov.ipset $MS_AZURE_URL_USGOV '.values[].properties.addressPrefixes[]'"
                  eval "./$run_microsoft_azure_usgov"

                  MS_AZURE_URL_GERMANY=$( curl -fsSL "${{ vars.BL_PRIVACY_MICROSOFT_AZURE_URL_GERMANY_SRC }}" | grep -o 'https://download.microsoft.com/download[^"]*ServiceTags_AzureGermany_[0-9]\+\.json' | head -n1 )
                  run_microsoft_azure_germany=".github/scripts/bl-json.sh blocklists/privacy/privacy_microsoft_azure_usgov.ipset $MS_AZURE_URL_GERMANY '.values[].properties.addressPrefixes[]'"
                  eval "./$run_microsoft_azure_germany"

                  MS_AZURE_URL_CHINA=$( curl -fsSL "${{ vars.BL_PRIVACY_MICROSOFT_AZURE_URL_CHINA_SRC }}" | grep -o 'https://download.microsoft.com/download[^"]*ServiceTags_China_[0-9]\+\.json' | head -n1 )
                  run_microsoft_azure_china=".github/scripts/bl-json.sh blocklists/privacy/privacy_microsoft_azure_china.ipset $MS_AZURE_URL_CHINA '.values[].properties.addressPrefixes[]'"
                  eval "./$run_microsoft_azure_china"

                  # #
                  #   Privacy › Nintendo
                  # #

                  run_nintendo=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_nintendo.ipset ${{ vars.BL_PRIVACY_NINTENDO_SRC }}"
                  eval "./$run_nintendo"

                  # #
                  #   Privacy › Oracle › OCI (EC2 / GCP)
                  # #

                  run_oracle_oci=".github/scripts/bl-json.sh blocklists/privacy/privacy_oracle_oci.ipset ${{ vars.BL_PRIVACY_ORACLE_OCI_SRC }} '.regions[].cidrs[] | select(.tags[] == \"OCI\") | .cidr'"
                  eval "./$run_oracle_oci"

                  # #
                  #   Privacy › Oracle › Oracle services network (OSN)
                  # #

                  run_oracle_osn=".github/scripts/bl-json.sh blocklists/privacy/privacy_oracle_osn.ipset ${{ vars.BL_PRIVACY_ORACLE_OSN_SRC }} '.regions[].cidrs[] | select(.tags[] == \"OSN\") | .cidr'"
                  eval "./$run_oracle_osn"

                  # #
                  #   Privacy › Oracle › Object Storage
                  # #

                  run_oracle_object_storage=".github/scripts/bl-json.sh blocklists/privacy/privacy_oracle_object_storage.ipset ${{ vars.BL_PRIVACY_ORACLE_OBJ_SRC }} '.regions[].cidrs[] | select(.tags[] == \"OBJECT_STORAGE\") | .cidr'"
                  eval "./$run_oracle_object_storage"

                  # #
                  #   Privacy › Oracle › All
                  # #

                  run_oracle_all=".github/scripts/bl-json.sh blocklists/privacy/privacy_oracle_all.ipset ${{ vars.BL_PRIVACY_ORACLE_ALL_SRC }} '.regions[].cidrs[] | .cidr'"
                  eval "./$run_oracle_all"

                  # #
                  #   Privacy › Pandora
                  # #

                  run_pandora=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_pandora.ipset ${{ vars.BL_PRIVACY_PANDORA_SRC }}"
                  eval "./$run_pandora"

                  # #
                  #   Privacy › Pingdom
                  # #

                  PINGDOM_IPv4=$( curl -sSL "${{ vars.BL_PRIVACY_PINGDOM_SRC }}/ipv4" \
                    | grep -vE '^(#|;|[[:space:]]*$)')
                  PINGDOM_IPv6=$( curl -sSL "${{ vars.BL_PRIVACY_PINGDOM_SRC }}/ipv6" \
                    | grep -vE '^(#|;|[[:space:]]*$)')
                  PINGDOM_LIST=$( echo -e "${PINGDOM_IPv4}\n${PINGDOM_IPv6}" | sort -u )
                  echo "$PINGDOM_LIST" | .github/scripts/bl-format.sh blocklists/privacy/privacy_pingdom.ipset

                  # #
                  #   Privacy › Pirate Bay
                  # #

                  run_piratebay=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_piratebay.ipset ${{ vars.BL_PRIVACY_PIRATEBAY_SRC }}"
                  eval "./$run_piratebay"

                  # #
                  #   Privacy › ProtonVPN
                  #   
                  #   Gathering these are tricky. Requires the authentication COOKIE / session_id to access API.
                  #     User Id     =>    secrets.BL_PRIVACY_PROTON_VPN_USERID
                  #     Cookie      =>    secrets.BL_PRIVACY_PROTON_VPN_AUTHCOOKIE
                  #     Session id  =>    secrets.BL_PRIVACY_PROTON_VPN_SESSIONID
                  # #

                  curl -s \
                    -H 'x-pm-appversion: AndroidVPN_5.5.52' \
                    -H 'x-pm-apiversion: 3' \
                    -H 'x-pm-locale: en_US' \
                    -H 'x-pm-uid: ${{ secrets.BL_PRIVACY_PROTON_VPN_USERID }}' \
                    -H 'cookie: ${{ secrets.BL_PRIVACY_PROTON_VPN_AUTHCOOKIE }}; Session-Id=${{ secrets.BL_PRIVACY_PROTON_VPN_SESSIONID }}; Tag=default; Theme=1; Domain=protonvpn.com; st=eyJ0IjoiZiIsImgiOiIwIn0' \
                    '${{ vars.BL_PRIVACY_PROTON_VPN_SRC }}' \
                  | jq -r '.LogicalServers[] | .Servers[]? | .EntryIP, .ExitIP, .ExitIPv6 | select(. != null)' \
                  | sort -u \
                  | .github/scripts/bl-format.sh blocklists/privacy/privacy_proton_vpn.ipset

                  # #
                  #   Privacy › Punkbuster
                  # #

                  run_punkbuster=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_punkbuster.ipset ${{ vars.BL_PRIVACY_PUNKBUSTER_SRC }}"
                  eval "./$run_punkbuster"

                  # #
                  #   Privacy › Riot Games
                  # #

                  run_riot_games=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_riot_games.ipset ${{ vars.BL_PRIVACY_RIOTGAMES_SRC }}"
                  eval "./$run_riot_games"

                  # #
                  #   Privacy › RSS API
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" ${{ vars.BL_PRIVACY_RSSAPI_SRC }} | .github/scripts/bl-format.sh blocklists/privacy/privacy_rssapi.ipset

                  # #
                  #   Privacy › Shadow Server
                  # #

                  run_facebook=".github/scripts/bl-whois.sh blocklists/privacy/privacy_shadowserver.ipset ${{ vars.BL_PRIVACY_SHADOWSERVER_SRC }}"
                  eval "./$run_facebook"

                  # #
                  #   Privacy › Steam
                  # #

                  run_steam=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_steam.ipset ${{ vars.BL_PRIVACY_STEAM_SRC }}"
                  eval "./$run_steam"

                  # #
                  #   Privacy › Stripe › API
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" "${{ vars.BL_PRIVACY_STRIPE_API_SRC }}" | .github/scripts/bl-format.sh blocklists/privacy/privacy_stripe_api.ipset

                  # #
                  #   Privacy › Stripe › Webhooks
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" "${{ vars.BL_PRIVACY_STRIPE_WEBHOOKS_SRC }}" | .github/scripts/bl-format.sh blocklists/privacy/privacy_stripe_webhooks.ipset

                  # #
                  #   Privacy › Stripe › Armada Gator
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" "${{ vars.BL_PRIVACY_STRIPE_ARMADA_GATOR_SRC }}" | .github/scripts/bl-format.sh blocklists/privacy/privacy_stripe_armada_gator.ipset

                  # #
                  #   Privacy › Sony Entertainment
                  # #

                  run_sony=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_sony.ipset ${{ vars.BL_PRIVACY_SONY_CORE_SRC }}"
                  eval "./$run_sony"

                  # #
                  #   Privacy › Telegram
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" "${{ vars.BL_PRIVACY_TELEGRAM_SRC }}" | .github/scripts/bl-format.sh blocklists/privacy/privacy_telegram.ipset

                  # #
                  #   Privacy › Tencent
                  # #

                  run_tencent=".github/scripts/bl-whois.sh blocklists/privacy/privacy_tencent.ipset ${{ vars.BL_PRIVACY_TENCENT_SRC }}"
                  eval "./$run_tencent"

                  # #
                  #   Privacy › Twitter / X
                  # #

                  run_twitter_x=".github/scripts/bl-whois.sh blocklists/privacy/privacy_twitter_x.ipset ${{ vars.BL_PRIVACY_TWITTER_X_SRC }}"
                  eval "./$run_twitter_x"

                  # #
                  #   Privacy › Ubisoft
                  # #

                  run_ubisoft=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_ubisoft.ipset ${{ vars.BL_PRIVACY_UBISOFT_SRC }}"
                  eval "./$run_ubisoft"

                  # #
                  #   Privacy › Uptime Robot
                  # #

                  curl -sSL -A "${{ env.USERAGENT }}" "${{ vars.BL_PRIVACY_UPTIMEROBOT_SRC }}" | .github/scripts/bl-format.sh blocklists/privacy/privacy_uptimerobot.ipset

                  # #
                  #   Privacy › WebPageTest
                  # #

                  curl -sSLk -A "${{ env.USERAGENT }}" "${{ secrets.PROXY_WEB_URL_HTTPS }}/json?url=https%3A%2F%2Fwebpagetest.org%2Faddresses.php%3Ff%3Djson" | jq -r '.data[].addresses[] | select( . != null )' | .github/scripts/bl-format.sh blocklists/privacy/privacy_webpagetest.ipset

                  # #
                  #   Privacy › Xfire
                  # #

                  run_xfire=".github/scripts/tool-range-iprange.sh blocklists/privacy/privacy_xfire.ipset ${{ vars.BL_PRIVACY_XFIRE_SRC }}"
                  eval "./$run_xfire"

            # #
            #   Generate › Spam
            # #

            - name: '🧱 Generate › Spam'
              id: task_blocklist_generate_spam
              run: |
                  run_spamhaus=".github/scripts/bl-plain.sh blocklists/spam/spam_spamhaus.ipset ${{ vars.BL_SPAM_SPAMHAUS_SRC }}"
                  eval "./$run_spamhaus"

            # #
            #   Generate › Spam › Forums
            #   
            #   only updated once per day (at 1am UTC)
            # #

            - name: '🧱 Generate › Spam › Forums (1/day)'
              id: task_blocklist_spam_generate_forums
              if: github.event_name == 'schedule' || ( github.event_name == 'workflow_dispatch' && inputs.RUN_ALL_ACTIONS == true )
              run: |
                  hour=$(date +'%H')
                  if [ "$hour" = "00" ]; then
                      chmod +x ".github/scripts/bl-plain.sh"
                      run_forums=".github/scripts/bl-plain.sh blocklists/spam/spam_forums.ipset ${{ vars.BL_SPAM_FORUMS_SRC }}"
                      eval "./$run_forums"
                  else
                      echo "Skipping daily-only task; not midnight"
                  fi

            # #
            #   Generate › Internet Service Provider
            #   
            #   @resources      https://ftp.arin.net/info/asn.txt
            #                   https://networksdb.io
            #                   https://rapidapi.com
            #                   https://ip.guide/
            #                   https://2ip.io
            #                   https://ip2location.com
            #                   https://ipqualityscore.com
            #                   https://ipinfo.io
            #                   https://radb.net
            #                   https://bgpview.io
            #   @info           script on another server is responsible for ensuring this workflow list is kept up to date with the correct ASN.
            #                   we use numerous resources to compare ASNs to see which ones are active and which ones have been migrated.
            # #

            - name: '🧱 Generate › ISP'
              id: task_blocklist_generate_isp
              run: |

                  # #
                  #   ISP › AOL
                  # #
              
                  run_isp_aol=".github/scripts/bl-block.sh blocklists/isp/isp_aol.ipset isp/aol.ipset"
                  eval "./$run_isp_aol"

                  # #
                  #   ISP › ATT
                  # #

                  run_isp_att=".github/scripts/bl-whois.sh blocklists/isp/isp_att.ipset AS7018"
                  eval "./$run_isp_att"

                  # #
                  #   ISP › Cablevision | Later merged with Suddenlink
                  # #

                  run_isp_cablevision=".github/scripts/bl-whois.sh blocklists/isp/isp_cablevision.ipset AS6128 AS13490 AS19720"
                  eval "./$run_isp_cablevision"

                  # #
                  #   ISP › Suddenlink / Altice / Optiumum
                  # #

                  run_isp_suddenlink_optimum=".github/scripts/bl-json.sh blocklists/isp/isp_suddenlink_altice_optimum.ipset https://ip.guide/AS19108 '.routes | .v4//empty,.v6//empty | .[]'"
                  eval "./$run_isp_suddenlink_optimum"

                  # #
                  #   ISP › Frontier Communications
                  #   https://networksdb.io/ip-addresses-of/cox-communications-inc
                  # #

                  run_isp_frontier=".github/scripts/bl-whois.sh blocklists/isp/isp_frontier_communications.ipset AS3593 AS5650 AS7011 AS26127 AS30064 AS32587"
                  eval "./$run_isp_frontier"

                  # #
                  #   ISP › Charter & Spectrum (Previously Time Warner Cable)
                  # #

                  run_isp_charter_spectrum=".github/scripts/bl-whois.sh blocklists/isp/isp_charter_spectrum_timewarnercable.ipset AS7843 AS11351 AS12271 AS20001 AS20115 AS3456 AS63365"
                  eval "./$run_isp_charter_spectrum"

                  # #
                  #   ISP › Comcast
                  # #

                  run_isp_comcast=".github/scripts/bl-whois.sh blocklists/isp/isp_comcast.ipset AS7922 AS7015 AS36732 AS36196 AS33651 AS33650 AS33542 AS33491 AS33490 AS33489 AS33351 AS33287 AS23266 AS23253 AS22909 AS22258 AS21508 AS20214 AS16748 AS14668 AS14042 AS13385 AS13367 AS11025"
                  eval "./$run_isp_comcast"

                  # #
                  #   ISP › Embarq
                  # #

                  run_isp_embarq=".github/scripts/bl-whois.sh blocklists/isp/isp_embarq.ipset AS22186 AS32855 AS2379 AS3447 AS4212 AS5778 AS6222 AS6367 AS11398 AS11530 AS13787 AS14905 AS14910 AS14921 AS16718 AS17402 AS18494 AS22186 AS32855"
                  eval "./$run_isp_embarq"

                  # #
                  #   ISP › Qwest
                  # #

                  run_isp_qwest=".github/scripts/bl-whois.sh blocklists/isp/isp_qwest.ipset AS3908 AS3909 AS3910 AS3951 AS4015 AS4911 AS6225 AS6226 AS6227 AS394190"
                  eval "./$run_isp_qwest"

                  # #
                  #   ISP › Sprint
                  # #

                  run_isp_sprint=".github/scripts/bl-whois.sh blocklists/isp/isp_sprint.ipset AS1239 AS150389 AS1789 AS1790 AS1791 AS1792 AS1793 AS1794 AS1795 AS197226 AS2014 AS2050 AS2053 AS206963 AS21288 AS2938 AS2942 AS2959 AS2981 AS3647 AS3648 AS3649 AS3650 AS3651 AS3652"
                  eval "./$run_isp_sprint"

                  # #
                  #   ISP › Verizon
                  #   https://networksdb.io/search/org/verizon
                  # #

                  run_isp_verizon=".github/scripts/bl-whois.sh blocklists/isp/isp_verizon.ipset AS701 AS702 AS1321 AS2125 AS7021 AS8385 AS6066 AS6167 AS9055 AS12367 AS22521"
                  eval "./$run_isp_verizon"

                  # #
                  #   ISP › Cox Communications
                  #   https://networksdb.io/ip-addresses-of/cox-communications-inc
                  # #

                  run_isp_cox=".github/scripts/bl-whois.sh blocklists/isp/isp_cox_communications.ipset AS31771 AS22773 AS13432 AS6298 AS12064 AS13493 AS15218 AS22318 AS25904 AS26204"
                  eval "./$run_isp_cox"

                  # #
                  #   ISP › SpaceX Starlink
                  # #

                  run_isp_starlink=".github/scripts/bl-whois.sh blocklists/isp/isp_spacex_starlink.ipset AS14593 AS397763 AS27277 AS142475"
                  eval "./$run_isp_starlink"

            # #
            #   Generate › Geographical › Geolite2 › Setup
            #   
            #   this step should only be ran once per day (at 1am UTC).
            #   The vars defined below are used for caching. The current day of the year + year are calculated, this allows
            #   the same cached files to be used in a 24 hour period. When the day of the year changes, a new set of geo files will
            #   be updated.
            #   
            #   CACHE VARS:           year_week       outputs the current week of the year, and year
            #                                         51_2024
            #   
            #                         year_day        outputs the current day of the year, and year
            #                                         308_2024
            # #

            - name: '🧱 Geographical › GeoLite2 (Setup)'
              id: task_blocklist_geographical_generate_setup
              if: github.event_name == 'schedule' || ( github.event_name == 'workflow_dispatch' && inputs.RUN_ALL_ACTIONS == true )
              run: |
                  hour=$(date +'%H')
                  if [ "$hour" = "00" ]; then
                      echo "year_week=$(date +'%U_%Y')" >> $GITHUB_ENV
                      echo "year_day=$(date +'%j_%Y')" >> $GITHUB_ENV
                  else
                      echo "Skipping daily-only task; not midnight"
                  fi

            # #
            #   Generate › Geographical › Geolite2 › Cache
            #   
            #   uses the same cache in a 24 hour period.
            #   
            #   @output               cache-hit
            #                         only run step if cache hit found
            #                         if: steps.task_blocklist_geographical_generate_cache.outputs.cache-hit == 'true'
            # #

            - name: '🧱 Geographical › GeoLite2 (Cache)'
              id: task_blocklist_geographical_generate_cache
              uses: actions/cache@v5
              if: steps.task_blocklist_geographical_generate_setup.outcome == 'success'
              with:
                  path: .github/.temp
                  key: cache-${{ runner.os }}-geolite2-${{ env.year_week }}

            # #
            #   Generate › Geographical › Geolite2 › Build
            # #

            - name: '🧱 Geographical › GeoLite2 (1/day)'
              id: task_blocklist_geographical_generate_geolite2
              if: steps.task_blocklist_geographical_generate_setup.outcome == 'success'
              run: |
                  chmod +x ".github/scripts/bl-geolite2.sh"
                  run_geolite2=".github/scripts/bl-geolite2.sh -l ${{ secrets.API_GEOLITE2_KEY }}"
                  eval "./$run_geolite2"

            # #
            #   Generate › Transmission
            # #

            - name: '🧱 Generate › Transmission'
              id: task_blocklist_generate_transmission
              run: |
                  run_bt=".github/scripts/bt-transmission.sh"
                  eval "./$run_bt"

            # #
            #   Delete Leftover Temps
            # #

            - name: '🧱 Generate › Cleanup Temps'
              id: task_blocklist_generate_cleanup
              run: |
                  echo "🧹 Cleaning up leftover .tmp files..."
                  find ./blocklists -type f -name '*.tmp' -print -delete
                  echo "✅ Cleanup complete."

            # #
            #   Generate › Verbose › List Tree
            # #

            - name: '🌲 Debug › Verbose Tree Listing'
              run: |
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
                  echo " PWD ..................... ${PWD}"
                  echo " GITHUB.WORKSPACE ........ ${{ github.workspace }}"
                  echo -e
                  echo -e
                  tree -I node_modules -I .git -I ./
                  echo "―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"

            # #
            #   Generate › SFTP / SSH › Upload Artifact
            # #

            #- name: 'SSH › Zip Artifacts'
            #  id: generate_artifact_zip
            #  run: |
            #      REPO_NAME="${{ github.event.repository.name }}"                         # csf-firewall
            #      BRANCH_NAME="${{ github.ref_name }}"                                    # main
            #      RUN_ID="${{ github.run_id }}"                                           # 17373119899

            #      ARTIFACT_NAME="artifact_${BRANCH_NAME}_${RUN_ID}.zip"                   # artifacts_main_xxxxxx.zip
            #      ARTIFACT_PATH="${REPO_NAME}/${ARTIFACT_NAME}"                           # csf-firewall/artifacts_main_xxxxxx.zip

            #      echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV                              # csf-firewall

            #      echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV                      # artifacts_main_xxxxxx.zip
            #      echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV                      # csf-firewall/artifacts_main_xxxxxx.zip

            #      echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT                   # artifacts_main_xxxxxx.zip
            #      echo "artifact-path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT                   # csf-firewall/artifacts_main_xxxxxx.zip

            #      zip -r "$ARTIFACT_NAME" ./*                                             # delete original zip before push

            # #
            #   Generate › SFTP / SSH › Setup SSH Key
            # #

            #- name: 'SSH › Upload Artifacts'
            #  run: |
            #      # Make sure the .ssh folder exists
            #      mkdir -p ~/.ssh
            #      echo "${{ secrets.ARTIFACTS_GITHUB_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/github_sftp_key"
            #      chmod 600 "$HOME/.ssh/github_sftp_key"

            #      # Upload to repo-specific directory
            #      sftp -P ${{ secrets.ARTIFACTS_PORT }} \
            #          -i "$HOME/.ssh/github_sftp_key" \
            #          -o StrictHostKeyChecking=no \
            #      github@${{ secrets.ARTIFACTS_DOMAIN }} <<EOF
            #      mkdir $REPO_NAME
            #      cd $REPO_NAME
            #      put $ARTIFACT_NAME
            #      bye
            #      EOF

            # #
            #   Generate › Artifact › Upload
            # #

            - name: "🎁 Generate › Upload Artifact"
              id: task_blocklist_generate_artifact_upload
              uses: actions/upload-artifact@v4
              with:
                  name: blocklist-latest
                  path: ./
                  retention-days: 1

    # #
    #   Job › Commit
    # #

    blocklist-commit:
        name: >-
          📋 Commit
        runs-on: ubuntu-latest
      # runs-on: apollo-x64
        timeout-minutes: 60
        needs: [ blocklist-setup, blocklist-generate ]
        steps:

            # #
            #   Commit › Checkout
            # #

            - name: >-
                  ☑️ Checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            # #
            #   Commit › Artifact › Setup SSH
            # #

            #- name: '🎁 Commit › Setup SSH Artifact'
            #  run: |
            #      mkdir -p ~/.ssh
            #      echo "${{ secrets.ARTIFACTS_GITHUB_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/github_sftp_key"
            #      chmod 600 "$HOME/.ssh/github_sftp_key"

            # #
            #   Commit › Artifact › Download
            # #

            #- name: '🎁 Commit › Download Artifact'
            #  run: |
            #      ARTIFACT_PATH="${{ needs.blocklist-generate.outputs.artifact-path }}"     # csf-firewall/artifacts_main_xxxxxx.zip
            #      ARTIFACT_NAME="$(basename "$ARTIFACT_PATH")"                              # artifacts_main_xxxxxx.zip
            #      REPO_NAME="$(dirname "$ARTIFACT_PATH")"                                   # csf-firewall

            #      echo "Downloading $ARTIFACT_PATH"

            #      sftp -P ${{ secrets.ARTIFACTS_PORT }} \
            #          -i "$HOME/.ssh/github_sftp_key" \
            #          -o StrictHostKeyChecking=no \
            #          github@${{ secrets.ARTIFACTS_DOMAIN }} <<EOF
            #      cd $REPO_NAME
            #      get $ARTIFACT_NAME
            #      bye
            #      EOF

            #      unzip -o "$ARTIFACT_NAME"                                                 # unzip -o artifacts_main_xxxxxx.zip
            #      rm -f "$ARTIFACT_NAME"                                                    # rm -f artifacts_main_xxxxxx.zip

            # #
            #   Commit › GPG › Import Key (No Passphrase)
            #   
            #   requires your GPG private key, converted to base64 binary .gpg (not armored .asc)
            #   
            #   this is utilized to generate signed hash digest
            #   
            #       find . -maxdepth 1 \( -name '*.zip' -o -name '*.gz' \) -printf '%P\n' | xargs -r sha1sum | gpg --digest-algo sha256 --clearsign > sha1sum.txt.asc
            #       find . -maxdepth 1 \( -name '*.zip' -o -name '*.gz' \) -printf '%P\n' | xargs -r sha256sum | gpg --digest-algo sha256 --clearsign > sha256
            # #

            - name: '🪪 Commit › GPG › Import Signing Key › W/o Passphrase'
              if: env.GPG_KEY_BASE64 != '' && env.GPG_KEY_PASSPHRASE == ''
              run: |
                  echo "$GPG_KEY_BASE64" | base64 -di | gpg --import

            # #
            #   Commit › GPG › Import Key (With Passphrase)
            #   
            #   requires your GPG private key, converted to base64 binary .gpg (not armored .asc)
            #   
            #   this is utilized to generate signed hash digest
            #   
            #       find . -maxdepth 1 \( -name '*.zip' -o -name '*.gz' \) -printf '%P\n' | xargs -r sha1sum | gpg --digest-algo sha256 --clearsign > sha1sum.txt.asc
            #       find . -maxdepth 1 \( -name '*.zip' -o -name '*.gz' \) -printf '%P\n' | xargs -r sha256sum | gpg --digest-algo sha256 --clearsign > sha256
            # #

            - name: '🪪 Commit › GPG › Import Signing Key › w/ Passphrase'
              if: env.GPG_KEY_BASE64 != '' && env.GPG_KEY_PASSPHRASE != ''
              run: |
                  echo "$GPG_KEY_BASE64" | base64 -di > /tmp/signing-key.gpg
                  echo "$GPG_KEY_PASSPHRASE" | gpg --pinentry-mode loopback --passphrase-fd 0 --import /tmp/signing-key.gpg
                  (echo "$GPG_KEY_PASSPHRASE"; echo; echo) | gpg --command-fd 0 --pinentry-mode loopback --change-passphrase $(gpg --list-secret-keys --with-colons 2> /dev/null | grep '^sec:' | cut --delimiter ':' --fields 5 | tail -n 1)

            # #
            #   Commit › Artifact › Download
            # #

            - name: "🎁 Commit › Download Artifact"
              id: task_commit_artifact_download
              uses: actions/download-artifact@v4
              with:
                  name: blocklist-latest
                  path: ./

            # #
            #   Commit › Precommit
            # #

            - name: "📦 Commit › Pre-commit"
              id: task_commit_pre
              run: |
                  now=$(date -u '+%m/%d/%Y %H:%M')
                  commit_label="Sync" >> $GITHUB_ENV
                  commit_message="\`️️🔒 $commit_label 🔒\` \`$now UTC\`" >> $GITHUB_ENV
                  echo "COMMIT_MESSAGE=$(echo $commit_message)" >> $GITHUB_ENV
                  echo "NOW=$(echo $now)" >> $GITHUB_ENV

            # #
            #   Commit › Update README
            # #

            - name: "📄 Commit › Update README"
              id: task_commit_readme_update
              run: |
                  chmod +x ".github/scripts/update-readme.sh"
                  run_readme=".github/scripts/update-readme.sh README.md"
                  eval "./$run_readme"

            # #
            #   Commit › GPG Key
            #   
            #   required in order to do signed commits
            # #

            - name: "📦 Commit › GPG Key"
              id: task_commit_gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.ADMINSERV_GPG_KEY_ASC }}
                  passphrase: ${{ secrets.ADMINSERV_GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true

            # #
            #   Commit › Commit
            # #

            - name: "📦 Commit › Execute"
              id: task_commit_execute
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: ${{ env.COMMIT_MESSAGE }}
                  commit_author: "${{ steps.task_commit_gpg.outputs.name }} <${{ steps.task_commit_gpg.outputs.email }}>"
                  commit_user_name: ${{ steps.task_commit_gpg.outputs.name }}
                  commit_user_email: ${{ steps.task_commit_gpg.outputs.email }}

            # #
            #   Commit › Clean up Artifacts
            #   
            #   Left-behind artifacts cleaned up after 5 days
            # #

        #   - name: '🎁 Commit › Cleanup Old Artifacts'
        #     run: |
        #         ssh -p ${{ secrets.ARTIFACTS_PORT }} \
        #         -i ~/.ssh/github_sftp_key \
        #         -o StrictHostKeyChecking=no \
        #         github@${{ secrets.ARTIFACTS_DOMAIN }} \
        #         "find ~/public_html -name 'artifacts_*.zip' -type f -mtime +5 -delete"
